### ISSUE TITLE
Support for DefiningQuery

### ISSUE THREAD

**Issue by dekenless** [boone34/Data.Entity.Edmx#3]
I know that the concept of DefiningQuery has been deprecated (https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#defining-query) but I was wondering if there was any thought to supporting this?

**Comment by boone34** [comment]
If it is depreciated I doubt I will support this.

**Comment by dekenless** [comment]
The guidance from the above link suggest simply using ToSqlQuery(), so would it be possible to do something like:

tity_builder.ToSqlQuery("SELECT  foo FROM Foo");
vs
entity_builder.ToTable("Foo", "dbo");

So, if the EDMX has a defining query use it in the ToSqlQuery method rather than generating a ToTable?

Or is it possible to tweak the T4 template on my one to make that happen (I had a look but I don't believe EntityType exposes DefiningQuery)?

**Comment by boone34** [comment]
In general this project is setup to allow users to customize the T4 templates so feel free to tweak away. Use the project template and modify the

- EdmxToEfCore/Generator.Context.ttinclude
- EdmxToEfCore/Generator.Model.ttinclude

files as needed.

_DefiningQuery_  is specified in the edmx SSDL element _EntitySet_.

In my xml serialization model it can be found in _TSsdlEntitySet.cs_.

This is simplified into _Model/Storage/EntitySet.cs_.

Unfortunately I did not add _DefiningQuery_ to _Model/Storage/EntitySet.cs_ though it would be trivial to do so.

Once added, in _/T4/EdmxToEfCore/Generator.Context.ttinclude_ I believe you would change:

`entity_builder.ToTable("<#= storage_entity_set.Table #>", "<#= storage_entity_set.Schema #>");`

to

`entity_builder.ToSqlQuery("<#= storage_entity_set.DefiningQuery #>");`

I will add _DefiningQuery_ to _Model/Storage/EntitySet.cs_ and let you know when done.

In addition to to the change suggested above you may need to check if _DefiningQuery_ is empty or null to choose whether to use _ToTable_ or _ToSqlQuery_.

**Comment by boone34** [comment]
I have added _DefiningQuery_ to _Model.Storage.EntitySet_.

**Comment by dekenless** [comment]
Great. Thanks.
